ERROR:sites:-- failed https://swissbinaryltd.com/indexoil.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexoil.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexoil.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexoil.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexoil.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexoil.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexoil.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexoil.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexoil.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexoil.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexoil.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexoil.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexoil.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexoil.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexgold.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexgold.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexgold.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexgold.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexoil.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexoil.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexgold.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexgold.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexgold.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexgold.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexgold.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexgold.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexoil.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexoil.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexgold.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexgold.html
ERROR:sites:-- failed https://swissbinaryltd.com/tools/swissbinaryltd-certificate.pdf
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/tools/swissbinaryltd-certificate.pdf
ERROR:sites:-- failed https://swissbinaryltd.com/indexoil.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexoil.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexgold.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexgold.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexoil.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexoil.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexgold.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexgold.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexgold.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexgold.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexgold.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexgold.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexgold.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexgold.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexoil.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexoil.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexgold.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexgold.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexoil.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexoil.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexgold.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexgold.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexoil.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexoil.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexgold.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexgold.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexoil.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexoil.html
ERROR:sites:-- failed https://swissbinaryltd.com/indexgold.html
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 222, in browse
    page = Page(link, session=self.session, base_url=self.base_url)
  File "/home/trevor/workspace/apps/clone/sites.py", line 35, in __init__
    self._content = self.get(self.url, session=session)
  File "/home/trevor/workspace/apps/clone/sites.py", line 44, in get
    raise PageNotFoundError(f'Page does not exist: {url}')
exceptions.PageNotFoundError: Page does not exist: https://swissbinaryltd.com/indexgold.html
ERROR:sites:file download failed
Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/cryptos/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/trevor/workspace/apps/clone/cryptos/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/trevor/workspace/apps/clone/cryptos/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/cryptos/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/trevor/workspace/apps/clone/cryptos/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/trevor/workspace/apps/clone/cryptos/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/trevor/workspace/apps/clone/cryptos/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/trevor/workspace/apps/clone/cryptos/lib/python3.8/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f23ef27e460>, 'Connection to www.apiinvestment.com timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/cryptos/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/trevor/workspace/apps/clone/cryptos/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/trevor/workspace/apps/clone/cryptos/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.apiinvestment.com', port=443): Max retries exceeded with url: /wp-content/uploads/2016/03/Agriculture-Real-Estate-Investment-Investing-Property-AgriBusiness-1.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f23ef27e460>, 'Connection to www.apiinvestment.com timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/trevor/workspace/apps/clone/sites.py", line 179, in download
    response = session.get(url, allow_redirects=True, timeout=10)
  File "/home/trevor/workspace/apps/clone/cryptos/lib/python3.8/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/trevor/workspace/apps/clone/cryptos/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/trevor/workspace/apps/clone/cryptos/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/trevor/workspace/apps/clone/cryptos/lib/python3.8/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.apiinvestment.com', port=443): Max retries exceeded with url: /wp-content/uploads/2016/03/Agriculture-Real-Estate-Investment-Investing-Property-AgriBusiness-1.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f23ef27e460>, 'Connection to www.apiinvestment.com timed out. (connect timeout=10)'))
